inherit_from: "VSLAM-Baselines/MonoGS/configs/mono/vslamlab/base_config.yaml"

Dataset:
  dataset_path: ""
  Calibration:
    fx: 0.0
    fy: 0.0
    cx: 0.0
    cy: 0.0
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 0
    height: 0
    distorted: False
